### ISSUE TITLE
What is your seed for generating the blue dog?

### ISSUE THREAD

**Issue by TiankaiHang** [gnobitab/FuseDream#5]
Some results
`python fusedream_generator.py --text 'A photo of a blue dog.' --seed 1234`
![fusedream_A photo of a blue dog _seed_1234_score_0 3833](https://user-images.githubusercontent.com/52823230/145161472-f271ec29-e868-4347-8477-684dc18aea35.png)
`python fusedream_generator.py --text 'A boy is reading papers.' --seed 1234`
![fusedream_A boy is reading papers_seed_1234_score_0 3416](https://user-images.githubusercontent.com/52823230/145161560-b6ba11db-144b-42bd-97d1-6ffdb8efed6a.png)

**Comment by TiankaiHang** [comment]
`python fusedream_generator.py --text 'A woman wearing lipstick.' --seed 1234`
![fusedream_A woman wearing lipstick_seed_1234_score_0 3476](https://user-images.githubusercontent.com/52823230/145161854-bd266fb1-41d0-4e9b-a032-5677043cb696.png)

**Comment by gnobitab** [comment]
Hi Tiankai,

Thank you for sharing with us your results!
I don't remember exactly the seed I used for that dog, but the default parameters in our colab should give you a good blue dog. Setting 'latent_noise=False' will give dogs with sharp edges with slightly smaller AugCLIP score.
Link to the colab: https://colab.research.google.com/drive/17qkzkoQQtzDRFaSCJQzIaNj88xjO9Rm9?usp=sharing
